FROM python:3.9-slim-buster
ENV PYTHONUNBUFFERED=1

RUN apt-get update -y && apt-get upgrade -y

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./app /code/app

COPY server.py server.py

COPY key.pem /code/key.pem

COPY cert.pem /code/cert.pem

CMD ["python" ,"server.py"]
